baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "ananke"

[params]
  author = "Your Name"
  description = "A description of your site"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

# Optional: Enable syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""

# Optional: Social media links
[[params.social]]
  name = "GitHub"
  url = "https://github.com/yourusername"

[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/yourusername"
